### ISSUE TITLE
Trying to update fails on accessing the network. (dns resolution) 

### ISSUE THREAD

**Issue by arthurlutz** [jeedom/core#106]
In a jeedom running inside of docker. dns resolution in bash is working fine. Trying to update fails on accessing the network. What's surprising is that it must have successfully connected to the internet at some point to get the information about the new versions available. 

```
[START UPDATE]
****Installation/Mise à jour de Jeedom 1.177.0 (2015-05-04 09:24:16)****
Paramètres de la mise à jour : level : -1, mode : , system : no 
[START BACKUP]
***************Lancement de la sauvegarde de Jeedom***************
Vérification du système de fichiers (corruption)...OK
Sauvegarde des fichiers...
OK
Suppression du fichier d'identification de la base de données...OK
Vérification de la base de données : 
jeedom.connection
note     : The storage engine for the table doesn't support check
Sauvegarde de la base de données...
OK
Création de l'archive...
OK
Nettoyage des anciennes sauvegardes...OK
Limite de la taille totale des sauvegardes à 200 Mo...***************Fin de la sauvegarde de Jeedom***************
[END BACKUP SUCCESS]
Desactivation de toutes les tâches
. OK
Désactivation de tous les scénarios OK
Nettoyage du dossier temporaire (tmp)...
OK
Adresse de téléchargement : https://market.jeedom.fr/jeedom/stable/jeedom.zip?timespamp=1430724301
Téléchargement en cours...PHP Warning:  fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /usr/share/nginx/www/jeedom/install/install.php on line 116
PHP Warning:  fopen(https://market.jeedom.fr/jeedom/stable/jeedom.zip): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /usr/share/nginx/www/jeedom/install/install.php on line 116
Réactivation des scénarios : OK
Réactivation des tâches : OK
Erreur durant l'installation : Echec lors du téléchargement du fichier. Veuillez réessayer plus tard (taille inférieure à 10 octets)Array
(
)
Details : 1[END UPDATE ERROR]
PHP Fatal error:  Uncaught exception 'Exception' with message 'Echec lors du téléchargement du fichier. Veuillez réessayer plus tard (taille inférieure à 10 octets)' in /usr/share/nginx/www/jeedom/install/install.php:121
Stack trace:
#0 {main}
  thrown in /usr/share/nginx/www/jeedom/install/install.php on line 121
``` 
The core of jeedom seems to say it's been updates (I don't think it's the case). Then on the modules :

```
                            [43] => Array
                                (
                                    [logicalId] => dashboard.info.binary.store
                                    [type] => widget
                                )
                            [44] => Array
                                (
                                    [logicalId] => dashboard.info.binary.timePresence
                                    [type] => widget
                                )
                            [45] => Array
                                (
                                    [logicalId] => dashboard.info.binary.window
                                    [type] => widget
                                )
                            [46] => Array
                                (
                                    [logicalId] => dashboard.info.binary.WindowIMG
                                    [type] => widget
                                )
                            [47] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.badge
                                    [type] => widget
                                )
                            [48] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.badge-Multiprise
                                    [type] => widget
                                )
                            [49] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.badge-transparent
                                    [type] => widget
                                )
                            [50] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.ConsoIMG
                                    [type] => widget
                                )
                            [51] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.gauge
                                    [type] => widget
                                )
                            [52] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.gaugeIMG
                                    [type] => widget
                                )
                            [53] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.heatPiloteWire
                                    [type] => widget
                                )
                            [54] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.humidite
                                    [type] => widget
                                )
                            [55] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.light
                                    [type] => widget
                                )
                            [56] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.luminosite
                                    [type] => widget
                                )
                            [57] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.luminositeIMG
                                    [type] => widget
                                )
                            [58] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.progressBar
                                    [type] => widget
                                )
                            [59] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.Round
                                    [type] => widget
                                )
                            [60] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.store
                                    [type] => widget
                                )
                            [61] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.tempIMG
                                    [type] => widget
                                )
                            [62] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.thermometre
                                    [type] => widget
                                )
                            [63] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.tile
                                    [type] => widget
                                )
                            [64] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.vibration
                                    [type] => widget
                                )
                            [65] => Array
                                (
                                    [logicalId] => dashboard.info.numeric.vuMeter
                                    [type] => widget
                                )
                            [66] => Array
                                (
                                    [logicalId] => dashboard.info.string.badge-transparent
                                    [type] => widget
                                )
                            [67] => Array
                                (
                                    [logicalId] => dashboard.info.string.maps
                                    [type] => widget
                                )
                            [68] => Array
                                (
                                    [logicalId] => dashboard.info.string.tile
                                    [type] => widget
                                )
                            [69] => Array
                                (
                                    [logicalId] => hasInternet.php
                                    [type] => script
                                )
                            [70] => Array
                                (
                                    [logicalId] => isConnected.sh
                                    [type] => script
                                )
                            [71] => Array
                                (
                                    [logicalId] => mobile.action.color.circle
                                    [type] => widget
                                )
                            [72] => Array
                                (
                                    [logicalId] => mobile.action.other.light
                                    [type] => widget
                                )
                            [73] => Array
                                (
                                    [logicalId] => mobile.action.other.lightIMG
                                    [type] => widget
                                )
                            [74] => Array
                                (
                                    [logicalId] => mobile.action.other.lock
                                    [type] => widget
                                )
                            [75] => Array
                                (
                                    [logicalId] => mobile.action.other.prise
                                    [type] => widget
                                )
                            [76] => Array
                                (
                                    [logicalId] => mobile.action.slider.button
                                    [type] => widget
                                )
                            [77] => Array
                                (
                                    [logicalId] => mobile.action.slider.kontrol
                                    [type] => widget
                                )
                            [78] => Array
                                (
                                    [logicalId] => mobile.action.slider.light
                                    [type] => widget
                                )
                            [79] => Array
                                (
                                    [logicalId] => mobile.action.slider.thermostat
                                    [type] => widget
                                )
                            [80] => Array
                                (
                                    [logicalId] => mobile.info.binary.alert
                                    [type] => widget
                                )
                            [81] => Array
                                (
                                    [logicalId] => mobile.info.binary.BaieIMG
                                    [type] => widget
                                )
                            [82] => Array
                                (
                                    [logicalId] => mobile.info.binary.door
                                    [type] => widget
                                )
                            [83] => Array
                                (
                                    [logicalId] => mobile.info.binary.doorIMG
                                    [type] => widget
                                )
                            [84] => Array
                                (
                                    [logicalId] => mobile.info.binary.light
                                    [type] => widget
                                )
                            [85] => Array
                                (
                                    [logicalId] => mobile.info.binary.lock
                                    [type] => widget
                                )
                            [86] => Array
                                (
                                    [logicalId] => mobile.info.binary.presence
                                    [type] => widget
                                )
                            [87] => Array
                                (
                                    [logicalId] => mobile.info.binary.prise
                                    [type] => widget
                                )
                            [88] => Array
                                (
                                    [logicalId] => mobile.info.binary.store
                                    [type] => widget
                                )
                            [89] => Array
                                (
                                    [logicalId] => mobile.info.binary.window
                                    [type] => widget
                                )
                            [90] => Array
                                (
                                    [logicalId] => mobile.info.numeric.badge
                                    [type] => widget
                                )
                            [91] => Array
                                (
                                    [logicalId] => mobile.info.numeric.gauge
                                    [type] => widget
                                )
                            [92] => Array
                                (
                                    [logicalId] => mobile.info.numeric.heatPiloteWire
                                    [type] => widget
                                )
                            [93] => Array
                                (
                                    [logicalId] => mobile.info.numeric.light
                                    [type] => widget
                                )
                            [94] => Array
                                (
                                    [logicalId] => mobile.info.numeric.progressBar
                                    [type] => widget
                                )
                            [95] => Array
                                (
                                    [logicalId] => mobile.info.numeric.Round
                                    [type] => widget
                                )
                            [96] => Array
                                (
                                    [logicalId] => mobile.info.numeric.store
                                    [type] => widget
                                )
                            [97] => Array
                                (
                                    [logicalId] => mobile.info.numeric.tempIMG
                                    [type] => widget
                                )
                            [98] => Array
                                (
                                    [logicalId] => mobile.info.numeric.tile
                                    [type] => widget
                                )
                            [99] => Array
                                (
                                    [logicalId] => mobile.info.numeric.vibration
                                    [type] => widget
                                )
                            [100] => Array
                                (
                                    [logicalId] => mobile.info.numeric.vuMeter
                                    [type] => widget
                                )
                            [101] => Array
                                (
                                    [logicalId] => neufBoxApi.php
                                    [type] => script
                                )
                            [102] => Array
                                (
                                    [logicalId] => WOL.php
                                    [type] => script
                                )
                        )
                    [1] => Array
                        (
                            [0] => beta
                            [1] => beta
                            [2] => beta
                            [3] => beta
                            [4] => beta
                            [5] => beta
                            [6] => stable
                            [7] => beta
                            [8] => beta
                            [9] => beta
                            [10] => beta
                            [11] => beta
                            [12] => beta
                            [13] => beta
                            [14] => beta
                            [15] => beta
                            [16] => beta
                            [17] => stable
                            [18] => stable
                            [19] => stable
                            [20] => stable
                            [21] => stable
                            [22] => stable
                            [23] => stable
                            [24] => stable
                            [25] => stable
                            [26] => stable
                            [27] => stable
                            [28] => stable
                            [29] => stable
                            [30] => stable
                            [31] => stable
                            [32] => stable
                            [33] => stable
                            [34] => stable
                            [35] => stable
                            [36] => stable
                            [37] => stable
                            [38] => stable
                            [39] => stable
                            [40] => stable
                            [41] => stable
                            [42] => stable
                            [43] => stable
                            [44] => stable
                            [45] => stable
                            [46] => stable
                            [47] => stable
                            [48] => stable
                            [49] => stable
                            [50] => stable
                            [51] => stable
                            [52] => stable
                            [53] => stable
                            [54] => stable
                            [55] => stable
                            [56] => stable
                            [57] => stable
                            [58] => stable
                            [59] => stable
                            [60] => stable
                            [61] => stable
                            [62] => stable
                            [63] => stable
                            [64] => stable
                            [65] => stable
                            [66] => stable
                            [67] => stable
                            [68] => stable
                            [69] => stable
                            [70] => stable
                            [71] => stable
                            [72] => stable
                            [73] => stable
                            [74] => stable
                            [75] => stable
                            [76] => stable
                            [77] => stable
                            [78] => stable
                            [79] => stable
                            [80] => stable
                            [81] => stable
                            [82] => stable
                            [83] => stable
                            [84] => stable
                            [85] => stable
                            [86] => stable
                            [87] => stable
                            [88] => stable
                            [89] => stable
                            [90] => stable
                            [91] => stable
                            [92] => stable
                            [93] => stable
                            [94] => stable
                            [95] => stable
                            [96] => stable
                            [97] => stable
                            [98] => stable
                            [99] => stable
                            [100] => stable
                            [101] => stable
                            [102] => stable
                        )
                )
        )
    [4] => Array
        (
            [file] => /usr/share/nginx/www/jeedom/install/install.php
            [line] => 64
            [function] => checkAllUpdate
            [class] => update
            [type] => ::
            [args] => Array
                (
                    [0] => 
                    [1] => 
                )
        )
)
Details : 1[END UPDATE ERROR]
PHP Fatal error:  Uncaught exception 'Exception' with message 'Impossible de résoudre le DNS : market.jeedom.fr. Pas d'internet ?' in /usr/share/nginx/www/jeedom/core/class/jsonrpcClient.class.php:91
Stack trace:
#0 /usr/share/nginx/www/jeedom/core/class/jsonrpcClient.class.php(40): jsonrpcClient->send(Array, 10, NULL, 3)
#1 /usr/share/nginx/www/jeedom/core/class/market.class.php(166): jsonrpcClient->sendRequest('market::byLogic...', Array)
#2 /usr/share/nginx/www/jeedom/core/class/market.class.php(356): market::byLogicalIdAndType(Array)
#3 /usr/share/nginx/www/jeedom/core/class/update.class.php(84): market::getInfo(Array, Array)
#4 /usr/share/nginx/www/jeedom/install/install.php(64): update::checkAllUpdate('', false)
#5 {main}
  thrown in /usr/share/nginx/www/jeedom/core/class/jsonrpcClient.class.php on line 91
```

**Comment by arthurlutz** [comment]
Successfully updated by adding ```37.187.67.222   market.jeedom.fr``` in my /etc/hosts

**Comment by arthurlutz** [comment]
@zoic21 can you explain why you are closing this issue ? Is it because I found a "workaround" ?

**Comment by zoic21** [comment]
Because docker image will be rebuild in 3 or 4 docker contener (one by service) and this issue wiil be fix in this new version
