### ISSUE TITLE
Error during installation on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by svergeylen** [jeedom/core#2067]
Hello,
 I am trying to install jeedom through the automated install.sh but the last step (10) seems to fail for a php issue. 
```

Commence l'étape 10 installation de jeedom
[START INSTALL]
****Install jeedom at (2022-09-30 17:54:03)****

Installation de Jeedom
Installation de la base de données...OK
Post installation...
[START CONSISTENCY]
[START CHECK AND FIX DB]
[END CHECK AND FIX DB]
Check jeedom package...warning: commands will be executed using /bin/sh
job 1 at Fri Sep 30 17:54:00 2022
OK
Check jeedom database...OK
PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in /var/www/html/core/class/DB.class.php:116
Stack trace:
#0 /var/www/html/core/class/DB.class.php(116): method_exists()
#1 /var/www/html/core/class/jeeObject.class.php(74): DB::Prepare()
#2 /var/www/html/core/class/config.class.php(366): jeeObject::all()
#3 /var/www/html/core/class/config.class.php(105): config::postConfig_object_summary()
#4 /var/www/html/install/consistency.php(68): config::save()
#5 /var/www/html/install/install.php(56): require_once('...')
#6 {main}
  thrown in /var/www/html/core/class/DB.class.php on line 116
Ne peut installer jeedom - Annulation
```

My php version was installed by the jeedom install script :

```
php --version
PHP 8.1.2 (cli) (built: Aug  8 2022 07:28:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

```

**Comment by ThibautTrarbach** [comment]
Hi,

For information, jeedom does not support ubuntu. It only supports debian.

Here is a link to the documentation with information on compatibility with jeedom :
https://doc.jeedom.com/en_US/compatibility/

Cordially
Thibaut

**Comment by kwizer15** [comment]
This is a real bug, and this is the php (not O/S) version that no longer accepts NULL as the first parameter of the method_exists function.
The code has to be corrected to deal with this case (but it probably won't be the only one).

**Comment by kwizer15** [comment]
@svergeylen try to install php7.4, it should be work.

**Comment by KiboOst** [comment]
Issues should be discussed on https://community.jeedom.com/
Regarding this, it is indeed a change in php8 which is not fully supported yet.
