### ISSUE TITLE
Export PNG "Field value too long"

### ISSUE THREAD

**Issue by Furaxworld** [jeedom/core#2535]
Salut,

Affichage historique, si modification de date lointaine, erreur https://export.highcharts.com/   lors de l'export du PNG

Chrome est à jour  --> Version 123.0.6312.123 (Build officiel) (64 bits)

`MulterError: Field value too long
    at abortWithCode (/var/app/current/node_modules/multer/lib/make-middleware.js:71:22)
    at Multipart.<anonymous> (/var/app/current/node_modules/multer/lib/make-middleware.js:78:34)
    at Multipart.emit (node:events:517:28)
    at SBMH.ssCb [as _cb] (/var/app/current/node_modules/busboy/lib/types/multipart.js:537:16)
    at feed (/var/app/current/node_modules/streamsearch/lib/sbmh.js:219:14)
    at SBMH.push (/var/app/current/node_modules/streamsearch/lib/sbmh.js:104:16)
    at Multipart._write (/var/app/current/node_modules/busboy/lib/types/multipart.js:567:19)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)`

![Animation](https://github.com/jeedom/core/assets/96196882/7962bf71-2556-4ef9-a7d0-6f01b0ff9455)

**Comment by zoic21** [comment]
Bonjour,
C'est normal l'export est un service gratuit et pour economiser des ressources ils doivent le limiter. Je pourrais rien y faire.
